apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bms-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host:   # replace with your domain or ALB DNS later
    http:
      paths:
      - path: /srikanth
        pathType: Prefix
        backend:
          service:
            name: bms-service
            port:
              number: 80
